### ISSUE TITLE
Add part attributes to docs-description content

### ISSUE THREAD

**Issue by christophe-g** [web-padawan/api-viewer-element#20]
Let's say I would like to style `h2` from a markdown description like: 

```md
 ## My new element

describe my element. 
```

I am aware I can use `::part(docs-description)` to set inherited css properties, like `font-family`. For instance, this will work (and all child elements from `[part=doc-description]` will inherit from the style): 

``` css
      api-viewer::part(docs-description) {
        font-family: 'Roboto', 'Noto', sans-serif;
        -webkit-font-smoothing: antialiased;  /* OS X subpixel AA bleed bug */
      }
```

However, what would be the option if I want to style a `h2` element within my markdown description? This for instance has no effect on h2 title element: 

```css
api-viewer::part(docs-description) h2 {
    font-size: 34px;
    font-weight: 400;
    letter-spacing: -.01em;
    line-height: 40px;
}
```

Any other better alternative than dynamically appending a `link[rel=stylesheet]` tag to `api-viewer-content` ?
